### ISSUE TITLE
is this updated to latest Auth0 requirements?

### ISSUE THREAD

**Issue by mrbm** [janat08/auth0-fetch#1]
I haven't researched this much, but after running the Cloudflare auth0 demo,  getting emails from auth0 titled:
Reminder - Action Required: Authorization Code and Access Token Variable Size

and then getting logs stating the depreciation with the following note:
Fixed Length of Access Token & Authorization Code: This feature is being deprecated. Please see https://auth0.com/docs/product-lifecycle/deprecations-and-migrations#opaque-access-token-for-userinfo for more information.

Has your package addressed the changes?

**Comment by janat08** [comment]
I don’t think it needs changes, as just stores the code as durable object id. They might exceed max length.

**Comment by janat08** [comment]
On the safer side codes could be stored on single DO state as a hash for lookup, I will close the issue as I don’t see your app failing.  Is the deprecation notice from logs a result of testing with min and max variable codes.
